# Generated by Django 5.1.2 on 2024-12-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование склада')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер полки')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование  полки')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='WareHouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.CharField(max_length=50, unique=True, verbose_name='PLU')),
                ('name', models.CharField(max_length=255, verbose_name='Наименованеи')),
                ('stock_on_shelf', models.IntegerField(verbose_name='Остаток на полке')),
                ('global_stock', models.IntegerField(verbose_name='Остаток в GK')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='WareHouse.shelf')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='WareHouse.warehouse')),
            ],
            options={
                'unique_together': {('shelf', 'warehouse')},
            },
        ),
    ]
