# Generated by Django 5.1.2 on 2024-12-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plu',
            field=models.CharField(max_length=50, verbose_name='PLU'),
        ),
    ]
