# Generated by Django 5.1.2 on 2024-12-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0002_alter_product_plu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shelf', 'warehouse', 'plu')},
        ),
    ]
