# Generated by Django 5.1.2 on 2024-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouse', '0004_inventory_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='accommodations',
            field=models.ManyToManyField(to='WareHouse.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('creating', 'Создается'), ('new', 'Создана'), ('collecting_data', 'Сбор данных'), ('pack', 'Выкладка'), ('close', 'Завершена')], default='open', max_length=35, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('pack_pending', 'Ожидает выкладки'), ('processed', 'Обработано')], default='pending', max_length=50, verbose_name='Статус обработки'),
        ),
    ]
