# Generated by Django 5.1.2 on 2024-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FPDD_DocConnectED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeOffs', models.CharField(max_length=200, unique=True, verbose_name='ID документа списания')),
                ('localInvent', models.CharField(max_length=200, unique=True, verbose_name='ID документа инвентаризации')),
                ('liCreationState', models.CharField(max_length=50, verbose_name='Статус документа коррекции')),
            ],
        ),
    ]
