# Generated by Django 5.1.2 on 2024-12-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpdd_docconnected',
            options={'verbose_name': 'Связка', 'verbose_name_plural': 'Связки'},
        ),
    ]
