# Generated by Django 5.1.5 on 2025-01-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0002_requestdatamatrixlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='admin_mode',
            field=models.BooleanField(default=False, verbose_name='Пользователь принимает административные сообщения'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_store_admin',
            field=models.BooleanField(default=False, verbose_name='Пользователь является административным?'),
        ),
        migrations.AlterField(
            model_name='requestdatamatrixlog',
            name='requets_is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
