# Generated by Django 5.1.2 on 2025-01-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=255)),
                ('record_id', models.IntegerField()),
                ('change_type', models.CharField(max_length=10)),
                ('new_state', models.JSONField()),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
