# Generated by Django 5.1.5 on 2025-01-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='app_label',
            field=models.CharField(default='WareHouse', max_length=50),
            preserve_default=False,
        ),
    ]
