# Generated by Django 5.1.2 on 2024-12-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGKApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.CharField(max_length=100, verbose_name='UUID'),
        ),
    ]
