# Generated by Django 5.1.2 on 2025-01-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGKApi', '0002_alter_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=2)),
                ('group_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'ordering': ['product_type', 'group_code'],
            },
        ),
    ]
