# Generated by Django 5.1.5 on 2025-01-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGKApi', '0003_productgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasureCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GKProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.IntegerField(unique=True)),
                ('shortName', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=100)),
                ('merchendiseGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WGKApi.productgroup')),
                ('unitOfMeasureCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WGKApi.unitofmeasurecode')),
            ],
        ),
    ]
